import DynamicArrayBasedStack from '../DynamicArrayBasedStack.js';
const stack = new DynamicArrayBasedStack(2);

console.log('将0入栈');
stack.push(0);
console.log('获取栈顶元素:', stack.peek());
console.log('将1入栈');
stack.push(1);
console.log('获取栈顶元素:', stack.peek());
console.log('是否为空栈', stack.isEmpty());
console.log('将2入栈');
stack.push(2);
console.log('将3入栈');
stack.push(3);
console.log('将4入栈');
stack.push(4);
console.log('获取栈顶元素:', stack.peek());
console.log('是否为空栈', stack.isEmpty());
console.log('将4出栈', stack.pop());
console.log('获取栈顶元素:', stack.peek());
console.log('将3出栈', stack.pop());
console.log('获取栈顶元素:', stack.peek());
console.log('将2出栈', stack.pop());
console.log('获取栈顶元素:', stack.peek());
console.log('将1出栈', stack.pop());
console.log('获取栈顶元素:', stack.peek());
console.log('将0出栈', stack.pop());
console.log('获取栈顶元素:', stack.peek());
console.log('是否为空栈', stack.isEmpty());